### ISSUE TITLE
Suggested Exclusion: Perl::Critic tests

### ISSUE THREAD

**Issue by kentfredric** [dagolden/TAP-Harness-Restricted#2]
Perl Critic tests are rare, but every time they exist such as that they run, they are landmine footguns.

Pod tests are problematic because the POD spec has changed from time to time, but Perl::Critic is orders of magnitude more annoying because the default configuration allows **any** critic policies to take place.

And there is of course tests in circulation that self-activate if Perl::Critic just happens to be installed.

http://grep.cpan.me/?q=Test%3A%3APerl%3A%3ACritic+file%3A.*\.t 

Fortunately, most of these examples have guards in place already in the form of ENV tokens.

However, they still serve as distracting cruft in the test logs that simply don't help.

**Comment by grr** [comment]
This passes the tests:

    diff --git a/lib/TAP/Harness/Restricted.pm b/lib/TAP/Harness/Restricted.pm
    index b0590a1..6d26442 100644
    --- a/lib/TAP/Harness/Restricted.pm
    +++ b/lib/TAP/Harness/Restricted.pm
    @@ -19,11 +19,20 @@ sub aggregate_tests {

    my $maybe_prefix = qr/(?:\d+[_-]?)?/;

    -my @banned_names =
    -  ( qr/${maybe_prefix}pod\.t/, qr/${maybe_prefix}pod[_-]?coverage\.t/, );
    +my @banned_names = (
    +    qr/${maybe_prefix}pod\.t/,
    +    qr/${maybe_prefix}pod[_-]?coverage\.t/,
    +    qr/${maybe_prefix}pod[_-]?spell(?:ing)?\.t/,
    +    qr/${maybe_prefix}perl[_-]?critic\.t/,
    +    qr/${maybe_prefix}kwalitee\.t/,
    +    qr/${maybe_prefix}author[_-].*\.t/,
    +);

    my @banned_code = (
    -    qr/use Test::Pod/, # also gets Test::Pod::Coverage
    +    qr/\b (?: use | require )\ Test::(?:
    +       Pod | Perl::Critic | Kwalitee | Spelling | Version | EOL | Vars
    +       | CleanNamespaces | Mojibake | NoTabs | Portability::Files
    +    )\b/x,
    );

    sub _file_ok {

**Comment by grr** [comment]
Another to add: Test::DependentModules

**Comment by xdg** [comment]
The 'author' one I would rather not have as I could see it being used for other things.

Want to send this as an actual PR?
